CREATE DATABASE ASSIGNMENT_1
USE ASSIGNMENT_1
SET SQL_SAFE_UPDATES = 0;
CREATE TABLE WORKER_1(
ID INT,
FIRST_NAME VARCHAR(25),
DEPARTMENT VARCHAR(25),
LOCATION VARCHAR(25),
SALARY INT
);
SELECT * FROM WORKER_1
INSERT INTO WORKER_1 VALUES(1,'AMITABH','DATA','LDH',45000);
INSERT INTO WORKER_1 VALUES(2,'MORISH','SALES','POP',45000);
INSERT INTO WORKER_1 VALUES(3,'RISHAV','DATA','KUC',47000);
INSERT INTO WORKER_1 VALUES(4,'VIPUL','SALES','DLI',48000);
INSERT INTO WORKER_1 VALUES(5,'SATISH','SALES','NDLS',49000);
INSERT INTO WORKER_1 VALUES(6,'ABHI','CONST','JUC',50000);
INSERT INTO WORKER_1 VALUES(7,'VIKAS','CONST','LUCK',51000);
SELECT * FROM WORKER_1

#Q1Write an SQL query to print the FIRST_NAME from Worker table after replacing ‘a’
with ‘A’.

SELECT REPLACE(FIRST_NAME,'A','a') from worker_1
SELECT * FROM WORKER_1 
 

Q2#Write an SQL query to print all Worker details from the Worker table order by
FIRST_NAME Ascending and DEPARTMENT Descending.


SELECT * FROM WORKER_1 ORDER BY FIRST_NAME ASC, DEPARTMENT DESC;

Q3. #Write an SQL query to fetch the names of workers who earn the highest salary.

SELECT FIRST_NAME, MAX(SALARY) FROM WORKER_1







